'use client';

import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { DynamicIcon } from '@/lib/icons';

interface Insight { title: string; detail: string; tone: 'positive' | 'suggestion' | 'warning' }

const TONE: Record<Insight['tone'], { icon: string; color: string }> = {
  positive:   { icon: 'trophy',   color: '#919191' },
  suggestion: { icon: 'zap',      color: '#555555' },
  warning:    { icon: 'flame',    color: '#a6a6a6' },
};

export default function CoachCard() {
  const [state, setState] = useState<'loading' | 'ready' | 'empty' | 'error'>('loading');
  const [insights, setInsights] = useState<Insight[]>([]);
  const [message, setMessage] = useState('');

  useEffect(() => {
    let active = true;
    (async () => {
      try {
        const res = await fetch('/api/coach');
        const json = await res.json();
        if (!active) return;
        if (!res.ok) { setMessage(json.error ?? 'Could not load insights'); setState('error'); return; }
        const list: Insight[] = json.data?.insights ?? [];
        if (list.length === 0) { setState('empty'); return; }
        setInsights(list);
        setState('ready');
      } catch {
        if (active) { setMessage('Network error'); setState('error'); }
      }
    })();
    return () => { active = false; };
  }, []);

  return (
    <div style={{ maxWidth: 480, margin: '0 auto', padding: '24px 20px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 18 }}>
        <div style={{
          width: 40, height: 40, borderRadius: 12, background: 'var(--surface-tint)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <DynamicIcon name="zap" size={20} color="#555555" />
        </div>
        <div>
          <h1 style={{ margin: 0, fontSize: 20, fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.02em' }}>
            Your Coach
          </h1>
          <p style={{ margin: '1px 0 0', fontSize: 12.5, color: 'var(--text-muted)' }}>
            Weekly insights from your habits
          </p>
        </div>
      </div>

      {state === 'loading' && (
        <p style={{ fontSize: 14, color: 'var(--text-muted)', padding: '24px 0', textAlign: 'center' }}>
          Reading your week…
        </p>
      )}

      {state === 'empty' && (
        <p style={{ fontSize: 14, color: 'var(--text-muted)', padding: '24px 0', textAlign: 'center' }}>
          Log a few habits and check back — your coach needs some data first.
        </p>
      )}

      {state === 'error' && (
        <p style={{ fontSize: 13.5, color: 'var(--danger)', padding: '20px 0', textAlign: 'center' }}>
          {message}
        </p>
      )}

      {state === 'ready' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {insights.map((ins, i) => {
            const t = TONE[ins.tone] ?? TONE.suggestion;
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.07, type: 'spring', damping: 26, stiffness: 280 }}
                style={{
                  background: 'var(--bg-card)', border: '1px solid var(--border-subtle)',
                  borderRadius: 18, padding: 16, display: 'flex', gap: 12,
                }}
              >
                <div style={{
                  width: 34, height: 34, flexShrink: 0, borderRadius: 10,
                  background: `${t.color}1a`, display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                  <DynamicIcon name={t.icon} size={17} color={t.color} />
                </div>
                <div>
                  <p style={{ margin: 0, fontSize: 14.5, fontWeight: 700, color: 'var(--text-primary)' }}>{ins.title}</p>
                  <p style={{ margin: '3px 0 0', fontSize: 13.5, lineHeight: 1.5, color: 'var(--text-secondary)' }}>{ins.detail}</p>
                </div>
              </motion.div>
            );
          })}
          <p style={{ margin: '6px 0 0', fontSize: 11, color: 'var(--text-muted)', textAlign: 'center' }}>
            Generated by AI from your data · refreshes weekly
          </p>
        </div>
      )}
    </div>
  );
}
